name: Build

on:
    push:
        branches:
            - 'main'

    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        name: Build

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: |
                  npm install -g npm@latest
                  npm ci

            - name: Build PDFs
              run: |
                  node makePdf.js https://d38l3k3yaet8r2.cloudfront.net/resources/products/epubs/generated/B7560A83-3047-4D3F-A203-B499F3BFAAAE/foxit-assets Year_12_HSC_Economics.pdf

            - uses: actions/upload-artifact@v2
              with:
                  name: PDFs
                  path: '*.pdf'
